"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        '''
        # collections.Counter类型的变量可相减，hash
        ds = collections.Counter(s)
        dt = collections.Counter(t)
        return (dt-ds).keys().pop()
        '''
        '''
        # approach2
        # t+s 多出来的字母次数为奇数
        d = collections.Counter(s+t)
        char = None
        for key, val in d.items():
            if val%2:
                char = key
        return char
        
        # approach3  位运算异或
        return chr(reduce(operator.xor, map(ord, s + t)))
        '''
        # approach4
        # str不可相减，但是数字可以相减
        res = ord(t[-1])
        for i in range(len(s)):
            res+= ord(t[i]) - ord(s[i])
        return chr(res)
